[package]
name = "flvparser"
version = "0.1.0"
authors = ["koushiro <koushiro.cqx@gmail.com>"]
repository = "https://github.com/koushiro/flvparser"
description = "A FLV file parsing library written in Rust with nom framework"
readme = "README.md"
license = "MIT"
keywords = ["flv", "parser"]

[[bin]]
name = "main"
path = "src/main.rs"

[dependencies]
nom = "4.0"
prettytable-rs = "^0.8"