[package]
name = "flvparser"
version = "0.1.0"
authors = ["koushiro <koushiro.cqx@gmail.com>"]
repository = "https://github.com/koushiro/flvparser"
description = "A FLV file parsing library written in Rust with nom framework"
readme = "README.md"
license = "MIT"
keywords = ["flv", "parser"]

[badges]
travis-ci = { repository = "koushiro/flvparser", branch = "master" }
appveyor = { repository = "koushiro/flvparser", branch = "master", service = "github" }
maintenance = { status = "actively-developed" }

[dependencies]
nom = "4.2"
clap = "2"
prettytable-rs = "^0.8"

[[bin]]
name = "main"
path = "src/main.rs"
