[workspace]
members = [".", "cmd"]
resolver = "3"

[workspace.package]
edition = "2024"
rust-version = "1.85.0"
license = "Apache-2.0"
homepage = "https://github.com/koushiro/flvparse"
repository = "https://github.com/koushiro/flvparse"

[package]
name = "flvparse"
version = "0.1.0"
authors = ["koushiro <koushiro.cqx@gmail.com>"]
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

description = "A FLV format parsing library written in Rust"
readme = "README.md"
documentation = "https://docs.rs/flvparse"
keywords = ["flv", "parse", "nom"]
exclude = ["assets", "cmd", "tests"]

[lib]
name = "flvparse"
path = "src/lib.rs"

[features]
default = ["std"]
std = ["nom/std"]

[dependencies]
nom = { version = "6.1", default-features = false, features = ["alloc"] }
