[package]
name = "flvparser"
version = "0.0.0"
authors = ["koushiro <koushiro.cqx@gmail.com>"]
description = "A FLV file parsing command line tool"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
anyhow = "1.0"
flvparse = { path = "../" }
clap = { version = "4.5", features = ["derive"] }
comfy-table = "7.2"
